# proxystaticfile
# 使用  ./proxystaticfile -c ./proxystaticfile.conf
# 默认挂载当前的的conf文件，配置文件使用 ini 格式输出
# 【情景】
#  用于代理均衡负载分布服务器的的静态文件输出，默认超时时间为30s

# 运行端口
port = "8808"
# 远程地址，在局域网中使用局域网地址；注意文件的相对路径
hosts = ["127.0.0.1","static.oschina.net"]
# 当前服务器端的文件所在地址
localDir = "/Users/erasin/Sites/tmp/"
